//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class baoHiem
    {
        public string maBH { get; set; }
        public int maNV { get; set; }
        public string noiCapso { get; set; }
        public string maLuong { get; set; }
        public Nullable<System.DateTime> ngayCap { get; set; }
        public string ghiChu { get; set; }
    
        public virtual Luong Luong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
