//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public string maHD { get; set; }
        public int maNV { get; set; }
        public string loaiHD { get; set; }
        public System.DateTime ngayBD { get; set; }
        public System.DateTime ngayKT { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
