//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNS1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-00HBHGV\\SQLEXPRESS;Initial Catalog=QLNhansu1;Integrated Secur" +
            "ity=True")]
        public string QLNhansu1ConnectionString {
            get {
                return ((string)(this["QLNhansu1ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-40TQM4C\\SQLEXPRESS;Initial Catalog=QLNhansu1;Integrated Secur" +
            "ity=True")]
        public string QLNhansu1ConnectionString1 {
            get {
                return ((string)(this["QLNhansu1ConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SC5S7G3\\SQLEXPRESS;Initial Catalog=QLNhansu1;Integrated Secur" +
            "ity=True")]
        public string QLNhansu1ConnectionString2 {
            get {
                return ((string)(this["QLNhansu1ConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHUCNGUYEN\\SQLEXPRESS;Initial Catalog=QLNhansu1;Integrated Security=T" +
            "rue")]
        public string QLNhansu1ConnectionString3 {
            get {
                return ((string)(this["QLNhansu1ConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-SKVRH89\\SQLEXPRESS;Initial Catalog=QLNhansu1;Integrated Secur" +
            "ity=True")]
        public string QLNhansu1ConnectionString4 {
            get {
                return ((string)(this["QLNhansu1ConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-18SF1ED\\MINHTIEN;Initial Catalog=QLNhansu1;Integrated Securit" +
            "y=True")]
        public string QLNhansu1ConnectionString5 {
            get {
                return ((string)(this["QLNhansu1ConnectionString5"]));
            }
        }
    }
}
